# EXPERIMENT-1

# #RGB IMAGE

In [1]:
# import cv2 module
import cv2

In [14]:
# read the image
img = cv2.imread(r"C:\Users\ASUS\Desktop\ROSE.jpeg")

In [15]:
#convert the image to RGB (images are read in BGR in OpenCV)
RGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

In [16]:
cv2.imshow("output", RGB)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
# shape prints the tuple (height,width,channels)
print(img.shape)

(222, 202, 3)


In [17]:
# img will be a numpy array of the above shape
print(img)

[[[255 255 255]
  [ 18  15  15]
  [ 18  15  15]
  ...
  [  0  19  34]
  [ 11  32  47]
  [ 23  46  62]]

 [[255 255 255]
  [ 16  15  15]
  [ 16  15  15]
  ...
  [  0   2  11]
  [  0   9  18]
  [  1  18  28]]

 [[255 255 255]
  [ 14  13  13]
  [ 14  13  13]
  ...
  [  0   6  11]
  [  0   7  14]
  [  0  13  18]]

 ...

 [[255 255 255]
  [  4  34  37]
  [ 27  56  59]
  ...
  [146 139 139]
  [148 139 140]
  [149 139 140]]

 [[255 255 255]
  [ 17  49  52]
  [ 35  66  69]
  ...
  [150 140 143]
  [151 140 143]
  [152 140 144]]

 [[255 255 255]
  [ 50  83  84]
  [ 61  93  95]
  ...
  [152 142 147]
  [153 142 147]
  [154 143 148]]]


Here 225*225 pixels are there and every pixel is an array of 3 integers (Red, Green, Blue)

### The single pixel can be extracted using indexing

In [18]:
# this is pixel of 0th row and 0th column
print(img[1][0])

[255 255 255]


# Grayscale Image

### Get grayscale then the pixel will just be a number representing the intensity of white.

In [4]:
import cv2